# Generated by Django 5.1.3 on 2024-11-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Houseplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=50)),
                ('scientific_name', models.CharField(max_length=50)),
                ('watering', models.CharField(max_length=7)),
                ('sunlight', models.CharField(max_length=13)),
                ('default_image', models.URLField()),
            ],
        ),
    ]
