# Generated by Django 5.1.3 on 2024-11-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Houseplant',
            new_name='Plant',
        ),
    ]
