# Generated by Django 5.1.3 on 2024-11-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_rename_houseplant_plant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='default_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='common_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='difficulty',
            field=models.CharField(default='Low', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='toxicity',
            field=models.CharField(default='Low', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(max_length=7),
        ),
    ]
