# Generated by Django 5.1.3 on 2024-11-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_plant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='owner',
        ),
    ]
